export interface ReportingTemplate {
  templateID: number;
  templateName: string;
  ownerID: number;
  ownerName: string;
  createdDate: string;
  lastUpdatedByUserID: number;
  lastUpdatedBy: string;
  lastUpdated: string;
  isGlobal: boolean;
  isDocWidget: boolean;
  isApiExport: boolean;
  isDeletable: boolean;
  isEditable: boolean;
  roleAccess: boolean;
  formattedCreatedDate: string;
  formattedLastUpdatedDate: string;
  isGlobalStringValue: string;
  isDocWidgetStringValue: string;
  isApiExportStringValue: string;
  isLocked: boolean;
  isLockedStringValue: string;
  showMore: boolean;
  budgetFormReportType: string | null;
  budgetFormDocType: string | null;
  orgId: string;
  settings_json: string;
  createdOrg: string;
  delegatedToSubLevel: boolean;
  delegatedToSubTenant: boolean;
  guidenceText: string;
  orgLevel: number;
  isUsedAsDynamicWidget: boolean;
  previousYearActuals: number;
  currentYearBudget: number;
  currentYearActuals: number;
  currentYearDeviation: number;
}

export const reportingData: any[] = [
  {
    "templateID": 1198,
    "templateName": "Driftsbudsjett med endringer - tilleggsinnstilling HP 2026-2029",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2025-09-17T11:07:13.737",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-09-25T12:05:59.077",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "17.09.2025",
    "formattedLastUpdatedDate": "25.09.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"budget_change\",\"org_name_2\",\"action\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\",\"external_description\",\"budget_phase\"],\"filterColumn\":[\"org_name_2\",\"budget_phase\",\"budget_change\"],\"conditionValues\":[[],[],[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15015}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 1250,
    "currentYearBudget": 2340,
    "currentYearActuals": 1890,
    "currentYearDeviation": -450
  },
  {
    "templateID": 1184,
    "templateName": "Totalt budsjett for hele kommunen for fremleggelse",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2025-08-06T10:47:03.233",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-09-11T11:16:47.94",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "06.08.2025",
    "formattedLastUpdatedDate": "11.09.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"org_name_4\",\"kostra_account\",\"kostra_account_name\",\"kostra_function\",\"kostra_function_name\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[],\"conditionValues\":[],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15015}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedTo SubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 1580,
    "currentYearBudget": 2750,
    "currentYearActuals": 990,
    "currentYearDeviation": -1760
  },
  {
    "templateID": 1181,
    "templateName": "Fordeling på programområder (brutto beløp)",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2025-06-26T09:05:14.73",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-09-02T08:04:11.127",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "26.06.2025",
    "formattedLastUpdatedDate": "02.09.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_id_2\",\"org_id_3\",\"org_name_3\",\"acc_group_code\",\"acc_group_description\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"org_id_2\",\"category\",\"acc_group_code\"],\"conditionValues\":[[],[],[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15015}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 2140,
    "currentYearBudget": 1820,
    "currentYearActuals": 3250,
    "currentYearDeviation": 1430
  },
  {
    "templateID": 1175,
    "templateName": "Driftstiltak Handlingsprogram",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2025-06-04T10:38:15.977",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-06-04T10:47:10.313",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "04.06.2025",
    "formattedLastUpdatedDate": "04.06.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"action_type\",\"action\",\"action_name_cab\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\",\"external_description\"],\"filterColumn\":[],\"conditionValues\":[],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":true,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 1890,
    "currentYearBudget": 3250,
    "currentYearActuals": 1470,
    "currentYearDeviation": -1780
  },
  {
    "templateID": 1161,
    "templateName": "Fordeling på programområder",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2025-03-31T11:47:50.753",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-09-02T08:04:20.597",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "31.03.2025",
    "formattedLastUpdatedDate": "02.09.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_id_2\",\"org_id_3\",\"org_name_3\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"org_id_2\",\"category\"],\"conditionValues\":[[],[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 2750,
    "currentYearBudget": 1420,
    "currentYearActuals": 3890,
    "currentYearDeviation": 2470
  },
  {
    "templateID": 1118,
    "templateName": "Budsjett per tjenesteområde",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2025-02-10T13:30:04.64",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-05-13T12:49:40.443",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "10.02.2025",
    "formattedLastUpdatedDate": "13.05.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_id_2_id_desc\",\"org_id_4\",\"org_name_4\",\"fk_account_code\",\"account\",\"kostra_function\",\"kostra_function_name\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[],\"conditionValues\":[],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15015}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 1520,
    "currentYearBudget": 2980,
    "currentYearActuals": 3340,
    "currentYearDeviation": 360
  },
  {
    "templateID": 1082,
    "templateName": "Alternative omstillingstiltak",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2024-09-23T08:59:02.33",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2024-10-08T12:59:19.463",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "23.09.2024",
    "formattedLastUpdatedDate": "08.10.2024",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"service_level_2_id_desc\",\"action\",\"category\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"category\"],\"conditionValues\":[[\"Ønskede tiltak\"]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[\"Ønskede tiltak\"],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 3150,
    "currentYearBudget": 1990,
    "currentYearActuals": 2450,
    "currentYearDeviation": 460
  },
  {
    "templateID": 1066,
    "templateName": "Tiltaksliste HP med Tiltaksstatus",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2024-05-28T08:36:23.437",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2024-09-23T08:57:20.143",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "28.05.2024",
    "formattedLastUpdatedDate": "23.09.2024",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"service_level_2_id_desc\",\"action\",\"category\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"category\"],\"conditionValues\":[[\"Parkerte tiltak\"]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[\"Parkerte tiltak\"],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 2340,
    "currentYearBudget": 1670,
    "currentYearActuals": 2890,
    "currentYearDeviation": 1220
  },
  {
    "templateID": 1034,
    "templateName": "Fordeling på programområde (tabell)",
    "ownerID": 15403,
    "ownerName": "Elin  Fejerskov",
    "createdDate": "2024-01-10T16:01:12.097",
    "lastUpdatedByUserID": 15403,
    "lastUpdatedBy": "Elin  Fejerskov",
    "lastUpdated": "2024-01-10T18:11:42.273",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "10.01.2024",
    "formattedLastUpdatedDate": "10.01.2024",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"service_level_2_id_desc\",\"org_id_3\",\"org_name_3\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"service_level_2_id_desc\",\"category\"],\"conditionValues\":[],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15403}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 1750,
    "currentYearBudget": 3620,
    "currentYearActuals": 2180,
    "currentYearDeviation": -1440
  },
  {
    "templateID": 1026,
    "templateName": "ID tiltak",
    "ownerID": 15012,
    "ownerName": "Kåre  Melheim",
    "createdDate": "2023-12-20T09:48:55.073",
    "lastUpdatedByUserID": 15012,
    "lastUpdatedBy": "Kåre  Melheim",
    "lastUpdated": "2023-12-20T09:48:55.073",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "20.12.2023",
    "formattedLastUpdatedDate": "20.12.2023",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"pk_action_id\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\",\"fk_department_code\",\"fk_account_code\",\"fk_function_code\"],\"filterColumn\":[\"pk_action_id\"],\"conditionValues\":[[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 2580,
    "currentYearBudget": 1340,
    "currentYearActuals": 3760,
    "currentYearDeviation": 2420
  },
  {
    "templateID": 1020,
    "templateName": "Tiltak pr ansvar",
    "ownerID": 15012,
    "ownerName": "Kåre  Melheim",
    "createdDate": "2023-12-01T11:53:56.773",
    "lastUpdatedByUserID": 15012,
    "lastUpdatedBy": "Kåre  Melheim",
    "lastUpdated": "2024-12-04T08:06:53.71",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.12.2023",
    "formattedLastUpdatedDate": "04.12.2024",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"fk_department_code\",\"department\",\"fk_function_code\",\"fp_year_1_amount\",\"action\"],\"filterColumn\":[\"fk_department_code\",\"fk_function_code\",\"action\"],\"conditionValues\":[[\"24100\",\"24130\",\"24150\",\"24200\",\"24250\",\"24300\",\"24330\",\"24350\",\"24400\",\"24450\",\"24500\",\"24550\",\"24600\",\"24650\",\"24700\",\"24750\",\"24800\",\"24830\",\"24850\",\"24900\",\"24950\",\"25000\",\"25050\",\"25100\",\"25130\",\"25150\",\"25200\",\"25250\",\"25300\",\"25350\",\"25400\",\"25450\",\"25500\",\"25550\",\"25600\",\"25650\",\"25700\",\"25750\",\"25800\",\"25850\",\"25900\",\"25950\",\"26000\",\"26050\",\"26100\",\"26150\",\"26200\",\"26230\",\"26250\",\"26300\",\"26350\",\"26400\",\"26450\",\"26500\",\"26550\",\"26600\",\"26650\",\"26700\",\"26750\",\"27500\",\"28000\",\"28100\",\"28200\",\"28300\",\"28400\",\"28500\",\"28600\",\"28700\",\"28800\",\"28900\",\"29000\",\"29100\",\"29130\"],[],[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[\"24100\",\"24130\",\"24150\",\"24200\",\"24250\",\"24300\",\"24330\",\"24350\",\"24400\",\"24450\",\"24500\",\"24550\",\"24600\",\"24650\",\"24700\",\"24750\",\"24800\",\"24830\",\"24850\",\"24900\",\"24950\",\"25000\",\"25050\",\"25100\",\"25130\",\"25150\",\"25200\",\"25250\",\"25300\",\"25350\",\"25400\",\"25450\",\"25500\",\"25550\",\"25600\",\"25650\",\"25700\",\"25750\",\"25800\",\"25850\",\"25900\",\"25950\",\"26000\",\"26050\",\"26100\",\"26150\",\"26200\",\"26230\",\"26250\",\"26300\",\"26350\",\"26400\",\"26450\",\"26500\",\"26550\",\"26600\",\"26650\",\"26700\",\"26750\",\"27500\",\"28000\",\"28100\",\"28200\",\"28300\",\"28400\",\"28500\",\"28600\",\"28700\",\"28800\",\"28900\",\"29000\",\"29100\",\"29130\"],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15012}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 3290,
    "currentYearBudget": 2150,
    "currentYearActuals": 1680,
    "currentYearDeviation": -470
  },
  {
    "templateID": 1019,
    "templateName": "Netto budsjett pr ansvar",
    "ownerID": 15012,
    "ownerName": "Kåre  Melheim",
    "createdDate": "2023-11-28T07:23:59.99",
    "lastUpdatedByUserID": 15012,
    "lastUpdatedBy": "Kåre  Melheim",
    "lastUpdated": "2023-11-28T08:04:43.207",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "28.11.2023",
    "formattedLastUpdatedDate": "28.11.2023",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"fk_department_code\",\"department\",\"fk_function_code\",\"fp_year_1_amount\"],\"filterColumn\":[\"fk_department_code\"],\"conditionValues\":[[\"24100\",\"24130\",\"24150\",\"24200\",\"24250\",\"24300\",\"24330\",\"24350\",\"24400\",\"24450\",\"24500\",\"24550\",\"24600\",\"24650\",\"24700\",\"24750\",\"24800\",\"24830\",\"24850\",\"24900\",\"24950\",\"25000\",\"25050\",\"25100\",\"25130\",\"25150\",\"25200\",\"25250\",\"25300\",\"25350\",\"25400\",\"25450\",\"25500\",\"25550\",\"25600\",\"25650\",\"25700\",\"25750\",\"25800\",\"25850\",\"25900\",\"25950\",\"26000\",\"26050\",\"26100\",\"26150\",\"26200\",\"26230\",\"26250\",\"26300\",\"26350\",\"26400\",\"26450\",\"26500\",\"26550\",\"26600\",\"26650\",\"26700\",\"26750\",\"27500\",\"28000\",\"28100\",\"28200\",\"28300\",\"28400\",\"28500\",\"28600\",\"28700\",\"28800\",\"28900\",\"29000\",\"29100\",\"29130\"]],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[\"24100\",\"24130\",\"24150\",\"24200\",\"24250\",\"24300\",\"24330\",\"24350\",\"24400\",\"24450\",\"24500\",\"24550\",\"24600\",\"24650\",\"24700\",\"24750\",\"24800\",\"24830\",\"24850\",\"24900\",\"24950\",\"25000\",\"25050\",\"25100\",\"25130\",\"25150\",\"25200\",\"25250\",\"25300\",\"25350\",\"25400\",\"25450\",\"25500\",\"25550\",\"25600\",\"25650\",\"25700\",\"25750\",\"25800\",\"25850\",\"25900\",\"25950\",\"26000\",\"26050\",\"26100\",\"26150\",\"26200\",\"26230\",\"26250\",\"26300\",\"26350\",\"26400\",\"26450\",\"26500\",\"26550\",\"26600\",\"26650\",\"26700\",\"26750\",\"27500\",\"28000\",\"28100\",\"28200\",\"28300\",\"28400\",\"28500\",\"28600\",\"28700\",\"28800\",\"28900\",\"29000\",\"29100\",\"29130\"],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15012}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 1960,
    "currentYearBudget": 3750,
    "currentYearActuals": 2280,
    "currentYearDeviation": -1470
  },
  {
    "templateID": 988,
    "templateName": "Fordeling på programområde",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-09-07T08:40:24.193",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-04-01T10:24:31.76",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "07.09.2023",
    "formattedLastUpdatedDate": "01.04.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_id_2\",\"org_name_3\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"org_id_2\"],\"conditionValues\":[[]],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15015}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 2840,
    "currentYearBudget": 1720,
    "currentYearActuals": 3960,
    "currentYearDeviation": 2240
  },
  {
    "templateID": 927,
    "templateName": "Driftsbudsjettet med endringer - tjenesteområde",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 7809459,
    "lastUpdatedBy": "Rudi  Hansen",
    "lastUpdated": "2022-11-16T13:29:25.653",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "16.11.2022",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"action_type\",\"action_name_cab\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":null,\"conditionValues\":null,\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":null,\"budgetFormReportType\":null,\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 3180,
    "currentYearBudget": 2640,
    "currentYearActuals": 1420,
    "currentYearDeviation": -1220
  },
  {
    "templateID": 918,
    "templateName": "Omstilling HP",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2024-09-26T09:06:37.033",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "26.09.2024",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"action\",\"alter_code\",\"fk_alter_code\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"fk_alter_code\"],\"conditionValues\":[[\"31\"]],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":null,\"filterToggleConditionValues\":[{\"filterValues\":[\"31\"],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 2460,
    "currentYearBudget": 3710,
    "currentYearActuals": 1980,
    "currentYearDeviation": -1730
  },
  {
    "templateID": 919,
    "templateName": "Driftsbudsjett med endringer",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2022-06-30T12:52:20.923",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "30.06.2022",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_1\",\"org_name_2\",\"action_type\",\"action_name_cab\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\",\"external_description\"],\"filterColumn\":null,\"conditionValues\":null,\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":null,\"budgetFormReportType\":null,\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 1790,
    "currentYearBudget": 2580,
    "currentYearActuals": 3340,
    "currentYearDeviation": 760
  },
  {
    "templateID": 921,
    "templateName": "Driftsbudsjett - Programområder",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2023-11-24T14:24:10.41",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "24.11.2023",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_2\",\"org_name_3\",\"fk_function_code\",\"fp_prev_year\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[],\"conditionValues\":[],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15015}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 3520,
    "currentYearBudget": 1690,
    "currentYearActuals": 2940,
    "currentYearDeviation": 1250
  },
  {
    "templateID": 947,
    "templateName": "Driftsbudsjett med endringer - tilleggsinnstilling",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2025-09-15T14:16:06.093",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": false,
    "isEditable": false,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "15.09.2025",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": true,
    "isLockedStringValue": "Låst",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"budget_change\",\"org_name_2\",\"action\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\",\"external_description\",\"budget_phase\"],\"filterColumn\":[\"budget_change\",\"budget_phase\",\"org_name_2\"],\"conditionValues\":[[],[\"Tilleggsinnstilling\"],[]],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":true,\"docType\":\"0\",\"budgetFormReportType\":null,\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[\"Tilleggsinnstilling\"],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": true,
    "previousYearActuals": 2310,
    "currentYearBudget": 3640,
    "currentYearActuals": 1750,
    "currentYearDeviation": -1890
  },
  {
    "templateID": 949,
    "templateName": "Utvikling netto driftsresultat",
    "ownerID": 15015,
    "ownerName": "Kathrine  Bolsø",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 15015,
    "lastUpdatedBy": "Kathrine  Bolsø",
    "lastUpdated": "2022-10-18T15:55:44.907",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "18.10.2022",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"acc_group_code\",\"acc_group_description\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"acc_group_code\",\"acc_group_description\"],\"conditionValues\":[[\"16\",\"18\",\"19\"]],\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":null,\"budgetFormReportType\":null,\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 1640,
    "currentYearBudget": 2970,
    "currentYearActuals": 3580,
    "currentYearDeviation": 610
  },
  {
    "templateID": 920,
    "templateName": "Budsjett per org nivå 3",
    "ownerID": 7795260,
    "ownerName": "Eirik  Helmen",
    "createdDate": "2023-01-01T00:00:00",
    "lastUpdatedByUserID": 7795260,
    "lastUpdatedBy": "Eirik  Helmen",
    "lastUpdated": "2022-06-21T09:41:25.757",
    "isGlobal": true,
    "isDocWidget": true,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2023",
    "formattedLastUpdatedDate": "21.06.2022",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Ja",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_name_3\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":null,\"conditionValues\":null,\"actionType\":\"Finplan\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":null,\"budgetFormReportType\":null,\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 2750,
    "currentYearBudget": 1980,
    "currentYearActuals": 3410,
    "currentYearDeviation": 1430
  },
  {
    "templateID": 869,
    "templateName": "Ansvar pr tjeneste",
    "ownerID": 15012,
    "ownerName": "Kåre  Melheim",
    "createdDate": "2022-01-01T00:00:00",
    "lastUpdatedByUserID": 15012,
    "lastUpdatedBy": "Kåre  Melheim",
    "lastUpdated": "2023-11-17T09:53:55.297",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2022",
    "formattedLastUpdatedDate": "17.11.2023",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"fk_account_code\",\"fk_department_code\",\"fk_function_code\",\"function\",\"org_name_2\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\"],\"filterColumn\":[\"fk_function_code\",\"fk_account_code\",\"fk_department_code\",\"budget_change\"],\"conditionValues\":[[],[],[\"21521\"],[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":\"0\",\"budgetFormReportType\":\"\",\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[\"21521\"],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":15012}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 3290,
    "currentYearBudget": 1540,
    "currentYearActuals": 2810,
    "currentYearDeviation": 1270
  },
  {
    "templateID": 740,
    "templateName": "Brutto budsjettrammer",
    "ownerID": 15227,
    "ownerName": "Sissel  Fredheim",
    "createdDate": "2020-01-01T00:00:00",
    "lastUpdatedByUserID": 15012,
    "lastUpdatedBy": "Kåre  Melheim",
    "lastUpdated": "2023-09-01T10:12:55.733",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2020",
    "formattedLastUpdatedDate": "01.09.2023",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"org_id_2\",\"org_name_2\",\"fp_year_1_amount\",\"fp_year_2_amount\",\"fp_year_3_amount\",\"fp_year_4_amount\",\"fp_year_1_amount_expence\",\"fp_year_2_amount_expence\",\"fp_year_3_amount_expence\",\"fp_year_4_amount_expence\",\"org_id_4\"],\"filterColumn\":[\"acc_group_code\",\"fk_function_code\",\"function\",\"org_id_2\"],\"conditionValues\":[[],[],[]],\"actionType\":\"All\",\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":null,\"budgetFormReportType\":null,\"filterToggleConditionValues\":[{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false},{\"filterValues\":[],\"filterToggle\":false,\"excludeFilterValues\":false}],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 1870,
    "currentYearBudget": 3490,
    "currentYearActuals": 2650,
    "currentYearDeviation": -840
  },
  {
    "templateID": 757,
    "templateName": "Budsjett per tjeneste 2020",
    "ownerID": 15008,
    "ownerName": "Anne Lise  Wibstad",
    "createdDate": "2020-01-01T00:00:00",
    "lastUpdatedByUserID": 15008,
    "lastUpdatedBy": "Anne Lise  Wibstad",
    "lastUpdated": "2019-08-06T06:48:03.8",
    "isGlobal": true,
    "isDocWidget": false,
    "isApiExport": false,
    "isDeletable": true,
    "isEditable": true,
    "roleAccess": false,
    "formattedCreatedDate": "01.01.2020",
    "formattedLastUpdatedDate": "06.08.2019",
    "isGlobalStringValue": "Felles",
    "isDocWidgetStringValue": "Nei",
    "isApiExportStringValue": "Nei",
    "isLocked": false,
    "isLockedStringValue": "Åpen",
    "showMore": false,
    "budgetFormReportType": null,
    "budgetFormDocType": null,
    "orgId": "AK",
    "settings_json": "{\"reportColumn\":[\"fk_function_code\",\"function\",\"org_name_2\",\"fp_year_1_amount\"],\"filterColumn\":[\"fk_function_code\"],\"conditionValues\":[[\"2340\",\"2341\",\"2342\"]],\"actionType\":null,\"includeBudgetAdjustment\":false,\"includeNonApprAdjCode\":false,\"fpActionReportOrgLevel\":null,\"objectType\":null,\"hideZeroRows\":false,\"docType\":null,\"budgetFormReportType\":null,\"filterToggleConditionValues\":[],\"displaySelectedTagsOnly\":false,\"displayCombinationTagsOnly\":false,\"createdBy\":0}",
    "createdOrg": "Asker kommune",
    "delegatedToSubLevel": false,
    "delegatedToSubTenant": false,
    "guidenceText": "",
    "orgLevel": 1,
    "isUsedAsDynamicWidget": false,
    "previousYearActuals": 2590,
    "currentYearBudget": 3120,
    "currentYearActuals": 1780,
    "currentYearDeviation": -1340
  }
];
